In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Dataset\FIFA PLAYER SKOR.csv')
df.head(5)

<>:1: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\F'
C:\Users\HP\AppData\Local\Temp\ipykernel_6416\1404250217.py:1: SyntaxWarning: invalid escape sequence '\F'
  df = pd.read_csv('Dataset\FIFA PLAYER SKOR.csv')

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640

In [21]:
df.isnull().sum()

Name                 0
Country              0
Position             0
Age                  0
Overall_Rating       0
Future Potential     0
Team                 0
Value Per M$         0
Total_Stats Score    0
dtype: int64

In [22]:
df.isna().sum()

Name                 0
Country              0
Position             0
Age                  0
Overall_Rating       0
Future Potential     0
Team                 0
Value Per M$         0
Total_Stats Score    0
dtype: int64

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19667 entries, 0 to 19666
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               19667 non-null  object
 1   Country            19667 non-null  object
 2   Position           19667 non-null  object
 3   Age                19667 non-null  int64
 4   Overall_Rating     19667 non-null  int64
 5   Future Potential   19667 non-null  int64
 6   Team               19667 non-null  object
 7   Value Per M$       19667 non-null  float64
 8   Total_Stats Score  19667 non-null  int64
dtypes: float64(1), int64(4), object(4)
memory usage: 1.4+ MB

In [77]:
df.head(5)

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640

### 1. Analisis Pemain & PosisiRata-rata Rating vs Harga: 
1. Posisi mana yang memiliki rata-rata Overall_Rating tertinggi, dan apakah posisi tersebut juga memiliki rata-rata Value Per M$ tertinggi?
2. Siapakah pemain "undervalued" (pemain dengan Overall_Rating tinggi namun memiliki Value Per M$ di bawah rata-rata)?
3. Berapa selisih antara Overall_Rating saat ini dengan Future Potential berdasarkan posisi pemain?

### 2. Analisis Umur & PotensiUsia Emas: 
1. Pada rentang usia (Age) berapakah pemain biasanya mencapai puncak Overall_Rating mereka?
2. Apakah ada korelasi yang kuat antara Future Potential seorang pemain muda dengan Value Per M$ mereka saat ini?
3. Siapakah 5 pemain muda (di bawah 21 tahun) yang memiliki selisih terbesar antara Overall_Rating dan Future Potential?

### 3. Analisis Negara & TimDominasi Negara:
1. Negara (Country) mana yang menyumbangkan pemain paling banyak dengan Overall_Rating di atas 85?
2. Tim (Team) manakah yang memiliki skuad paling efisien (rata-rata Total_Stats Score tinggi namun total Value Per M$ rendah)?
3. Distribusi Statistik: Bagaimana distribusi Total_Stats Score pemain jika dibandingkan antar negara?

### 4. Analisis Nilai EkonomiPenentu Harga:
1. apakah Overall_Rating ataukah Future Potential?
2. Apakah pemain dengan Total_Stats Score yang tinggi selalu memiliki harga jual (Value Per M$) yang tinggi pula?
3. Jika kita mengelompokkan pemain berdasarkan Age, bagaimana tren penurunan Value Per M$ seiring bertambahnya usia pemain?

### 5. Analisis StatistikOutlier Performa: 
1. Siapakah pemain yang memiliki Total_Stats Score tertinggi namun tidak bermain di Team besar?
2. Bagaimana perbandingan rata-rata Total_Stats Score untuk pemain dengan posisi Goalkeeper dibandingkan dengan posisi Midfielder?

In [78]:
df.head(5)

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640

### 1. Analisis Pemain & PosisiRata-rata Rating vs Harga: 
1. Posisi mana yang memiliki rata-rata Overall_Rating tertinggi, dan apakah posisi tersebut juga memiliki rata-rata Value Per M$ tertinggi?
2. Siapakah pemain "undervalued" (pemain dengan Overall_Rating tinggi namun memiliki Value Per M$ di bawah rata-rata)?
3. Berapa selisih antara Overall_Rating saat ini dengan Future Potential berdasarkan posisi pemain?

In [ ]:
# soal nomor 1
meanRating = df.groupby('Position')[['Overall_Rating']].mean()
meanValue= df.groupby('Position')[['Value Per M$']].mean()

topRatingPos = meanRating.idxmax()
topRatingVal = meanRating.max()

topValuePos = meanValue.idxmax()
topValueVal = meanValue.max()


print(f"Posisi rata-rata Overall Rating tertinggi: {topRatingPos.values[0]} => ({topRatingVal.values[0]})")
print(f"Posisi rata-rata Value Per M$ tertinggi: {topValuePos.values[0]} => ({topValueVal.values[0].round(2)} M$)")
print("kesimpulan: Posisi RF tidak memiliki Value yang tinggi")

Posisi rata-rata Overall Rating tertinggi: RF => (75.0)
Posisi rata-rata Value Per M$ tertinggi: CF => (4.28 M$)
kesimpulan: Posisi RF tidak memiliki Value yang tinggi

In [169]:
# soal nomor 2
topRating= df['Overall_Rating'].max()
meanValue = df['Value Per M$'].mean()
pemain_termahal = df.loc[((df['Overall_Rating'] == topRating) & (df['Value Per M$']< meanValue)), ['Name','Team']]

hasil = pemain_termahal['Name'].iloc[0] if not pemain_termahal.empty else "Pemain yang dimaksud tidak ada"
print(f"Pemain tersebut adalah: {hasil}")

Pemain tersebut adalah: Pemain yang dimaksud tidak ada

In [ ]:
#soal nomor 3
df['Gap_potential']= df['Overall_Rating'] - df['Future Potential']
gapPerposition = df.groupby('Position')[['Gap_potential']].mean().sort_values(by='Gap_potential',ascending=False)
gapPerposition

          Gap_potential
Position
SW            -4.000000
RF            -4.000000
RWB           -6.269360
CDM           -6.613402
LWB           -6.930000
LM            -7.042220
RM            -7.059850
CF            -7.139286
LB            -7.161230
CB            -7.241865
RB            -7.382727
ST            -7.422321
LW            -7.429439
RW            -7.667610
GK            -8.004237
CM            -8.017950
CAM           -8.123749